services:
  - type: web
    name: adverse-weather-classifier
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
      - key: CUDA_VISIBLE_DEVICES
        value: ""
    healthCheckPath: /
